name: orocomputer_system
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.8.3
  google_nav_bar: ^5.0.7
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  
  assets:
    - assets/auth.env
    - assets/images/Oro.png